Docs: features and definitions
vektonn/vektonn pull request #10
Opened 2022-02-07 09:46 UTC by streamoverflow

2022-02-09 12:20 UTC, AndrewKostousov requested changes

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/features.md
> +We have a very thin and efficient management layer atop of actual binary indexes, so the overhead is almost non-existent.
Я думаю, "overhead is almost non-existent" - это слишком большое преувеличение. По крайней мере, по имеющимся у нас на текущий момент данным.

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/features.md
> +#### Data splitting and filtering
"splitting" и "filtering" в нашей картине мира - это слова, обозначающие одну и ту же фичу. Меня смутил предлог "and" в заголовке.

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/features.md
> +We support changing indexes as new data arrives (delete, change, or add data to the index), in parallel with search queries.
in parallel -> concurrently лучше?

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/features.md
> +You can expand multiple indexes over a single data source (vectors and attributes) and seamlessly transition to new versions of indexes. You can expand different indexes with different parameters of
Слово "expand", кажется, тут не подходит. Может быть, заменить на "deploy"?

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/features.md
> +You can adjust the indexing scheme for specific filter values for a more efficient search.
Тут наверное надо все же попродробнее раскрыть, что дает сплитинг.

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +    PayloadAttribute: set[AttributeKey]
PayloadAttributeS

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +PermanentAttributes ⋂ DataAttributes ≡ ∅
PayloadAttributes

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +### Sharding
Я все еще думаю, что без доп пояснений этот раздел "спеки" про шардирование не очень-то помогает понять, как у нас реализован шардинг. Тут с одной стороны какие-то очень мелкие детали описываются (типа взятия модуля от хэша), а с другой какие-то вещи не специфицированы (та же хэш-функция).

Предлагаю просто удалить его.

2022-02-09 12:20 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +## Searching
Можно добавить аналогичную спеку про загрузку данных через апишку (раздел Data upload)

2022-02-09 12:28 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +AttributeValue := bool | int | float | str | UUID | datetime
Лучше использовать int64, float64 для понимания размеров типов данных.

2022-02-09 12:31 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +IndexMeta := (
Сейчас [представление IndexMeta в коде](https://github.com/vektonn/vektonn/blob/master/src/Vektonn.SharedImpl/Contracts/IndexMeta.cs) гораздо лучше структурировано. В частности, выделился [DataSourceMeta](https://github.com/vektonn/vektonn/blob/master/src/Vektonn.SharedImpl/Contracts/DataSourceMeta.cs) картой типов для всех атрибутов.

Мне кажется, лучше текущее состояние исходников в эту спеку перенести максимально близко к тексту. Разве что про шардирование DataSource-ов можно тут не упоминать.

2022-02-09 12:36 UTC, AndrewKostousov commented on docs/reference/supported-algorithms.md
> +- `FaissIndex.Flat.L2`
Слова Flat теперь в типе Faiss-алгоритма нет. Зато есть словарь с параметрами. Если он пустой, будет Flat-индекс создан. А если в нем есть HNSW-параметры, то HNSW-индекс.

2022-02-18 05:56 UTC, AndrewKostousov commented on docs/reference/supported-algorithms.md
> +| HNSW <BR> (Hierarchical Navigable Small World graph exploration) | `FaissIndex.L2`, params: {"M", "efConstruction", "efSearch" }   |
HNSW и для IP-метрики работает.

Вообще, это ортогональные вещи - тип индекса и метрика. Возможно стоит это так и подавать: мол, вот какие метрики можно в FAISS-индексах использовать (IP и L2); а дальше, если нужен быстрый но приближенный поиск, указываем HNSW-параметры, в противном случае строится Flat-индекс для точного поиска.

Можно еще ссылку на доку FAISS-а дать по метрикам: https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances

2022-02-18 06:18 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +)
Тут еще не хватает карты типов значений для всех атрибутов (AttributeValueTypes)

2022-02-18 06:20 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +    vectorDimension: int,
А вот тут int32.

Я все же предлагаю везде в этом псевдокоде использовать явные int32, int64, float64. Так запутаться сложнее и потом проще будет обвновлять доку, если мы будем поддержку других примитивных типов добавлять.

2022-02-18 06:26 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +DataSource := (metadata: DataSourceMeta, timeline: list[DataPointUpdate])
Предлагаю в этой "спеке" на псевдо-коде оставить только описание схемы (метаданных) сорцов и индексов. А DataPointUpdate расписать в разделе "Data upload" ниже.

2022-02-18 06:48 UTC, AndrewKostousov requested changes

2022-02-18 06:48 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +AttributeValue := bool | int | float | str | UUID | datetime
Раз уж ты python-style стал использовать, можно тут `Union[bool, int64, ...]` написать...

2022-02-18 06:48 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +All **other attributes** are `PayloadAttributes` — any metadata to store alongside the vector, may be freely updated.
Надо по всей статье пройтись и к одному виду naming полей привести - или camelCase, или PascalCase.

2022-02-18 06:48 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +Index's permanent attributes must be a subset of a corresponding data source's permanent attributes. They cannot be changed during vector's lifetime.
Нет, множество permanentAttributes задается на уровне дата-сорца и наследуется всеми индексами над ним.

2022-02-18 06:48 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +Tombstone := (idAttributes: Attributes)  # uniquely identify a data point to delete
Ключом для записи в кафку [служит](https://github.com/vektonn/vektonn/blob/master/src/Vektonn.DataSource/Kafka/KafkaDataSourceProducer.cs#L62) набор всех permanentAttributes.

2022-02-23 22:28 UTC, streamoverflow commented on docs/reference/definitions.md
> +    vectorDimension: int,
Мне кажется это излишне, оно не имеет значения какой именно целый тип здесь. Целый — и ладно. Не хочется перегружать спеку совсем уж лишними деталями.

2022-02-23 22:29 UTC, streamoverflow commented on docs/reference/definitions.md
> +AttributeValue := bool | int | float | str | UUID | datetime
В `3.10` это [вполне себе валидный синтаксис](https://docs.python.org/3/library/typing.html#typing.Union).

2022-02-23 22:32 UTC, streamoverflow commented on docs/reference/definitions.md
> +All **other attributes** are `PayloadAttributes` — any metadata to store alongside the vector, may be freely updated.
Тут какое дело: есть типы (они с заглавной), а есть поля объектов — их я решил писать со строчной, чтобы чуть ближе к принятому в Питоне и чтобы отличались от типов. Совсем снейк-кейс неохота, чтобы не противоречило сишарповой части (и находилось поиском).

Тем не менее, вроде, где-то я кейсы всё же перепутал — пройдусь приведу к одному виду.

2022-02-23 22:35 UTC, streamoverflow commented on docs/reference/definitions.md
> +Index's permanent attributes must be a subset of a corresponding data source's permanent attributes. They cannot be changed during vector's lifetime.
Да, я это видел. Здесь у нас же перманентные атрибуты — это объединение `Id+Split+Shard`. Мы же можем не все перманентные атрибуты явно использовать в каждом индексе.

Стоит переформулирорвать понятнее?

2022-02-23 22:36 UTC, streamoverflow commented on docs/reference/definitions.md
> +Tombstone := (idAttributes: Attributes)  # uniquely identify a data point to delete
Да, я это видел. Осталось с первой версии спеки, когда постоянных атрибутов явно ещё не было. Поправлю.

2022-02-23 22:40 UTC, streamoverflow commented on docs/reference/definitions.md
> +)
Тут я не хотел переусложнять и опустил. Кажется, что это несущественная деталь и для общей семантики достаточно просто множества атрибутов.

2022-02-23 23:18 UTC, streamoverflow commented on docs/reference/definitions.md
> +DataSource := (metadata: DataSourceMeta, timeline: list[DataPointUpdate])
Ниже добавлять мне не нравится, потому что мы определяем датасорс как `timeline: list[DataPointUpdate]`, т.е. ссылаемся на `DataPointUpdate`. Объявлять его в совсем другой секции, тем более ниже, а не выше, будет сбивать с толку.

2022-02-24 06:34 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +)
Мне кажется, типы данных атрибутов - это весьма существенная деталь. Как минимум, напрямую влияющая на затраты по памяти. Кроме того, и это наверное даже важнее - дают ответ на вопрос, а что именно можно в атрибуты сложить.

2022-02-24 06:43 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +    vectorDimension: int,
Ты же выше написал, что "Both `int` and `float` are 64-bit". Возникает справедливый WTF: зачем размерность векторов делать long-ом.

Кроме того, я считаю, что запись float64 лучше чем float, а запись int64 лучше чем int с пояснением про битность текстом. Это придает спеке четкости без лишних усложнений.

2022-02-24 07:04 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +DataSource := (metadata: DataSourceMeta, timeline: list[DataPointUpdate])
О том и речь, чтобы урать декларации дата-сорца с этим timeline-ом. Я смотрю на этот раздел как на описание "схемы данных". С этой точки зрения - нормально унести описание процесса наполенения дата-сорца в другой раздел.

Чтобы пользоваться Вектоном, нужно задать схему дата-сорцов и индексов, и данный раздел призван пояснить, как это сделать. Разделы про наполнеие дата-сорцов и поиск в индексах проясняют, как выглядят соответствующие API-шки.

2022-02-24 07:04 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +AttributeValue := bool | int | float | str | UUID | datetime
А, ну ок тогда.

2022-02-24 07:18 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +Index's permanent attributes must be a subset of a corresponding data source's permanent attributes. They cannot be changed during vector's lifetime.
Сущности "перманентные атрибуты в индексе" нет в исходниках, и потребности в ней как таковой нет. Более того, сейчас и payloadAttributes ты выбрать не можешь - в индекс попадают все атрибуты, объявленные в дата-сорце:
```
public HashSet<string> IndexPayloadAttributes => DataSourceMeta.AttributeValueTypes.Keys.Except(IdAttributes).Except(SplitAttributes).ToHashSet();
```

2022-02-24 08:26 UTC, streamoverflow commented on docs/reference/definitions.md
> +Tombstone := (idAttributes: Attributes)  # uniquely identify a data point to delete
Кстати, в [Tombstone.cs](https://github.com/vektonn/vektonn/blob/master/src/Vektonn.SharedImpl/Contracts/Tombstone.cs) оно ещё значится как `IdAttributes`.

2022-02-24 08:27 UTC, streamoverflow commented on docs/reference/definitions.md
> +Index's permanent attributes must be a subset of a corresponding data source's permanent attributes. They cannot be changed during vector's lifetime.
Чуточку переформулировал

2022-02-24 08:27 UTC, streamoverflow commented on docs/reference/definitions.md
> +All **other attributes** are `PayloadAttributes` — any metadata to store alongside the vector, may be freely updated.
Привёл к единому виду.

2022-02-24 08:29 UTC, streamoverflow commented on docs/reference/supported-algorithms.md
> +| HNSW <BR> (Hierarchical Navigable Small World graph exploration) | `FaissIndex.L2`, params: {"M", "efConstruction", "efSearch" }   |
Может быть, сделать 1-в-1 как в [Vektonn.Index](https://github.com/vektonn/vektonn-index#supported-index-types-and-metrics)? Проще поддерживать будет — все обновления просто копипастить во второе место.

2022-02-24 08:31 UTC, streamoverflow commented on docs/reference/definitions.md
> +## Searching
Попробовал добавить раздел, покрутил туда-сюда и пока не нашёл устраивающего меня варианта, сочетающегося с разделом про датасорс.

2022-02-24 08:32 UTC, streamoverflow commented on docs/reference/definitions.md
> +Tombstone := (idAttributes: Attributes)  # uniquely identify a data point to delete
Пока тут переименовал в `permanentAttributes` .

2022-02-24 08:38 UTC, AndrewKostousov commented on docs/reference/definitions.md
> +Tombstone := (idAttributes: Attributes)  # uniquely identify a data point to delete
Точно. Поправлю это в [ветке v0.7](https://github.com/vektonn/vektonn/tree/v0.7).

2022-02-24 08:40 UTC, AndrewKostousov commented on docs/reference/supported-algorithms.md
> +| HNSW <BR> (Hierarchical Navigable Small World graph exploration) | `FaissIndex.L2`, params: {"M", "efConstruction", "efSearch" }   |
Да, давай это унифицируем.

2022-03-17 21:11 UTC, streamoverflow commented on docs/reference/definitions.md
> +## Searching
Добавил раздел `Updating data`

2022-03-17 21:11 UTC, streamoverflow commented on docs/reference/supported-algorithms.md
> +| HNSW <BR> (Hierarchical Navigable Small World graph exploration) | `FaissIndex.L2`, params: {"M", "efConstruction", "efSearch" }   |
Унифицировал

2022-03-17 21:23 UTC, streamoverflow commented on docs/reference/definitions.md
> +)
Типы добавил, но не стал подробно расписывать (примерно то же уже есть в описании датапоинтов)

2022-03-17 21:25 UTC, streamoverflow commented on docs/reference/definitions.md
> +DataSource := (metadata: DataSourceMeta, timeline: list[DataPointUpdate])
Таймлайн убрал.

2022-03-17 21:27 UTC, streamoverflow commented
Добавил ещё разделы про шардинг и сплиттинг.

2022-03-21 08:20 UTC, merged